##===- frontend/Makefile -----------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL = ../../../local/download/llvm-svn/objdir
LIBRARYNAME = pinapa
LOADABLE_MODULE = 1
USEDLIBS =
LINK_COMPONENTS=core
KEEP_SYMBOLS=1
CXXFLAGS=-g

include $(LEVEL)/Makefile.common
